package com.ampf.soapdemo.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2025-04-13T16:17:27.622+05:30
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://controller.soapDemo.ampf.com/", name = "EmployeeController")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeController {

    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://controller.soapDemo.ampf.com/", className = "com.ampf.soapdemo.controller.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://controller.soapDemo.ampf.com/", className = "com.ampf.soapdemo.controller.InitResponse")
    public void init();

    @WebMethod
    @RequestWrapper(localName = "empDetails", targetNamespace = "http://controller.soapDemo.ampf.com/", className = "com.ampf.soapdemo.controller.EmpDetails")
    @ResponseWrapper(localName = "empDetailsResponse", targetNamespace = "http://controller.soapDemo.ampf.com/", className = "com.ampf.soapdemo.controller.EmpDetailsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String empDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://controller.soapDemo.ampf.com/", className = "com.ampf.soapdemo.controller.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://controller.soapDemo.ampf.com/", className = "com.ampf.soapdemo.controller.GetAllEmployeesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Employee> getAllEmployees();
}
