package com.ampf.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-06-02T15:57:18.360+05:30
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://controller.ampf.com/", name = "StudentSOAPController")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentSOAPController {

    @WebMethod
    @RequestWrapper(localName = "getStudentAddress", targetNamespace = "http://controller.ampf.com/", className = "com.ampf.controller.GetStudentAddress")
    @ResponseWrapper(localName = "getStudentAddressResponse", targetNamespace = "http://controller.ampf.com/", className = "com.ampf.controller.GetStudentAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getStudentAddress()
;

    @WebMethod
    @RequestWrapper(localName = "getStudentName", targetNamespace = "http://controller.ampf.com/", className = "com.ampf.controller.GetStudentName")
    @ResponseWrapper(localName = "getStudentNameResponse", targetNamespace = "http://controller.ampf.com/", className = "com.ampf.controller.GetStudentNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getStudentName()
;
}
